version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_DATABASE: coder-java
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
